name: Deploy Individual Lambdas

on:
  push:
    branches:
      - main

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      lambda1: ${{ steps.filter.outputs.lambda1 }}
      lambda2: ${{ steps.filter.outputs.lambda2 }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            lambda1:
              - 'src/lambda1/**'
            lambda2:
              - 'src/lambda2/**'

  deploy-lambda1:
    needs: filter
    if: needs.filter.outputs.lambda1 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip Lambda1 Code
        run: |
          cd src/lambda1
          zip -r ../../lambda1.zip index.js
          cd ../../
      - name: Deploy to AWS Lambda (lambda1)
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: lambda1
          zip_file: lambda1.zip

  deploy-lambda2:
    needs: filter
    if: needs.filter.outputs.lambda2 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip Lambda2 Code
        run: |
          cd src/lambda2
          zip -r ../../lambda2.zip index.js
          cd ../../
      - name: Deploy to AWS Lambda (lambda2)
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: lambda2
          zip_file: lambda2.zip
